# Generated by Django 4.2.8 on 2024-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=1000)),
                ('img_source', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
