# Generated by Django 4.2.8 on 2024-03-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_item_href_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.CharField(default='', max_length=30),
        ),
    ]
