# Generated by Django 4.2.11 on 2024-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
