# Generated by Django 4.2.11 on 2024-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_item_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
    ]
