# Generated by Django 4.2.11 on 2024-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='other food', max_length=200),
        ),
    ]
