# Generated by Django 4.2.11 on 2024-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='buf',
            field=models.CharField(default='', max_length=200),
        ),
    ]
