# Generated by Django 4.2.11 on 2024-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_test_image_upload_item_buf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buf',
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
