# Generated by Django 4.2.11 on 2024-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_remove_item_buf_item_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
