# Generated by Django 4.2.11 on 2024-04-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_item_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.item')),
            ],
        ),
    ]
